---
Ancho: 10
Alto: 9

Mapa:
  - ['P', 'P', 'P', 'P', 'A', 'A', 'A', 'A', 'A', 'A']
  - ['R', 'R', 'R', 'R', 'P', 'A', 'A', 'A', 'A', 'A']
  - ['R', 'R', 'R', 'R', 'P', 'A', 'A', 'A', 'A', 'A']
  - ['R', 'R', 'R', 'R', 'R', 'A', 'A', 'A', 'A', 'A']
  - ['A', 'C', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A']
  - ['A', 'C', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A']
  - ['R', 'R', 'R', 'R', 'R', 'D', 'D', 'D', 'A', 'A']
  - ['P', 'P', 'P', 'P', 'P', 'D', 'D', 'D', 'A', 'A']
  - ['A', 'A', 'A', 'A', 'A', 'D', 'D', 'D', 'A', 'A']
  