---
Ancho: 10
Alto: 9

Mapa:
  - ['P', 'P', 'P', 'P', 'A', 'A', 'A', 'A', 'A', 'A']
  - ['R', 'R', 'R', 'R', 'P', 'A', 'A', 'A', 'A', 'A']
  - ['R', 'R', 'R', 'R', 'P', 'A', 'A', 'A', 'A', 'A']
  - ['R', 'R', 'R', 'R', 'R', 'A', 'A', 'A', 'A', 'A']
  - ['A', 'C', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A']
  - ['A', 'C', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A']
  - ['R', 'R', 'R', 'R', 'R', 'D', 'D', 'D', 'A', 'A']
  - ['P', 'P', 'P', 'P', 'P', 'D', 'D', 'D', 'A', 'A']
  - ['A', 'A', 'A', 'A', 'A', 'D', 'D', 'D', 'A', 'A']

Mapa2:
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']
  - ['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']

Silo:
  Valor: 0x03
  Posicion:
    XArena: 5
    YArena: 1
    XPrecipicio: 0
    YPrecipicio: 0
    XCima: 1
    YCima: 4
    XDuna: 5
    YDuna: 6
    XRoca: 0
    YRoca: 1
